stages:
  - build
  - unit test
  - integrations test

build site:
  image: node:10
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

unit:
  image: node:10
  stage: unit test
  script:
    - npm install --progres:false
    - npm run test:unit

e2e:
  image: node:10
  stage: integrations test
  services:
    - selenium/standalone-firefox
    - selenium/standalone-chrome
  script:
    - npm run test:e2e --host=selenium__standalone-firefox
    - npm run test:e2e --host=selenium__standalone-chrome
