build site:
  image: node:10
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

test:
  image: node:10
  stage: test
  script:
    - npm install --progres:false
    - npm run test:unit
    - npm run test:e2e --env firefox,chrome [--headless]
