stages:
  - build
  - unit test
  - integrations test

build site:
  image: node:10
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

unit:
  image: node:10
  stage: unit test
  script:
    - npm install --progres:false
    - npm run test:unit

e2e:
  image: node:10
  stage: integrations test
  services:
    - selenium/standalone-firefox
    - selenium/standalone-chrome
  script:
    - npm install --progres:false
    - npm run test:e2e --host=selenium__standalone-firefox
    - npm run test:e2e --host=selenium__standalone-chrome
  before_script:
    - apt-get update
    # Install Chrome
    - apt-get install -yq libnss3 unzip openjdk-8-jre-headless xvfb libxi6 libgconf-2-4
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - curl -sS -o - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
    - apt install -y ./google-chrome-stable_current_amd64.deb
    # Install Firefox
    - apt-get install -y firefox-esr
